"$schema" = "https://www.schemastore.org/bunfig.json"

[run]
bun = true

[install]
auto = "disable"
linker = "isolated"
peer = false
minimumReleaseAge = 604800 # 7 days
# TODO: Remove "wrangler"; just for debugging a CI deployment issue.
minimumReleaseAgeExcludes = ["@maxmilton/*", "bugbox", "stage1", "wrangler"]

[test]
preload = ["./test/setup.ts"]
