name: shellcheck
on:
  push:
    branches: [master, next]
    paths: ["**.sh", ".github/workflows/shellcheck.yml"]
  pull_request: {}
  merge_group: {}
  workflow_dispatch: {}
  schedule:
    - cron: "28 6 * * 4"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - run: shellcheck -ax **/*.sh
        shell: bash
